#undef COMMAND_ROLES
#undef SECURITY_ROLES
#undef SUPPLY_ROLES
#undef MEDICAL_ROLES
#undef RESEARCH_ROLES
#undef ENGINEERING_ROLES
#undef EXPLORATION_ROLES

#undef CIVILIAN_BRANCHES
#undef COMBAT_BRANCHES
#undef TERRAGOV_BRANCHES
