/datum/map/intrepid/bolt_saferooms()
	for(var/atype in typesof(/area/intrepid/department/civillian/safe_room))
		var/area/A = locate(atype)
		if(istype(A))
			for(var/obj/machinery/door/airlock/vault/bolted/V in A.contents)
				if(!V.locked)
					V.lock()

/datum/map/intrepid/unbolt_saferooms()
	for(var/atype in typesof(/area/intrepid/department/civillian/safe_room))
		var/area/A = locate(atype)
		if(istype(A))
			for(var/obj/machinery/door/airlock/vault/bolted/V in A.contents)
				if(V.locked)
					V.unlock()

/datum/map/intrepid/ship_jump()
	for(var/obj/effect/overmap/visitable/ship/intrepid/intrepid)
		new /obj/effect/temp_visual/ftl (get_turf(intrepid))
		animate(intrepid, alpha = 0, color = COLOR_BLUE, time = 1 SECONDS)
		QDEL_IN(intrepid, (1 SECONDS))
