name: Run Tests

permissions:
  contents: read

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
env:
  BYOND_MAJOR: "513"
  BYOND_MINOR: "1527"
  SPACEMAN_DMM_VERSION: suite-1.5

jobs:
  PreFlight:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: paths-filter
        uses: dorny/paths-filter@b2feaf19c27470162a626bd6fa8438ae5b263721
        id: filter
        with:
          filters: .github/workflow-config/preflight-filters.yml
    outputs:
      dm: ${{ steps.filter.outputs.dm }}
  DreamChecker:
    runs-on: ubuntu-latest
    needs: PreFlight
    if: needs.PreFlight.outputs.dm == 'true'
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: Setup Cache
        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353
        with:
          path: $HOME/spaceman_dmm/$SPACEMAN_DMM_VERSION
          key: ${{ runner.os }}-spacemandmm-${{ env.SPACEMAN_DMM_VERSION }}
      - name: Install Dreamchecker
        run:  scripts/install-spaceman-dmm.sh dreamchecker
      - name: Run Dreamchecker
        run: ~/dreamchecker > ${GITHUB_WORKSPACE}/output-annotations.txt 2>&1
      - name: Annotate Lints
        uses: yogstation13/DreamAnnotate@34029606cd7c22a08a589e084f860c1cc287363c
        if: always()
        with:
          outputFile: output-annotations.txt
      - name: Run Failure Webhook
        env:
          JOB_STATUS: ${{ job.status }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          HOOK_OS_NAME: ${{ runner.os }}
          WORKFLOW_NAME: ${{ github.workflow }}
        if: ${{ failure() }}
        run: |
          wget https://raw.githubusercontent.com/DiscordHooks/github-actions-discord-webhook/master/send.sh
          chmod +x send.sh
          ./send.sh failure $WEBHOOK_URL
  Code:
    runs-on: ubuntu-latest
    needs: PreFlight
    if: needs.PreFlight.outputs.dm == 'true'
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: Setup Cache
        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353
        with:
          path: $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
          key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      - name: Install Dependencies
        run: sudo apt-get install -y uchardet
      - name: Run Tests
        env:
          TEST: CODE
        run: test/run-test.sh
      - name: Run Failure Webhook
        env:
          JOB_STATUS: ${{ job.status }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          HOOK_OS_NAME: ${{ runner.os }}
          WORKFLOW_NAME: ${{ github.workflow }}
        if: ${{ failure() }}
        run: |
          wget https://raw.githubusercontent.com/DiscordHooks/github-actions-discord-webhook/master/send.sh
          chmod +x send.sh
          ./send.sh failure $WEBHOOK_URL
  ExampleMap:
    runs-on: ubuntu-latest
    needs: PreFlight
    if: needs.PreFlight.outputs.dm == 'true'
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Setup Cache
        uses: actions/cache@fd5de65bc895cf536527842281bea11763fefd77
        with:
          path: $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
          key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      - name: Run Tests
        env:
          TEST: MAP
          MAP_PATH: example
        run: test/run-test.sh
      - name: Run Failure Webhook
        env:
          JOB_STATUS: ${{ job.status }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          HOOK_OS_NAME: ${{ runner.os }}
          WORKFLOW_NAME: ${{ github.workflow }}
        if: ${{ failure() }}
        run: |
          wget https://raw.githubusercontent.com/DiscordHooks/github-actions-discord-webhook/master/send.sh
          chmod +x send.sh
          ./send.sh failure $WEBHOOK_URL
  TorchMap:
    runs-on: ubuntu-latest
    needs: PreFlight
    if: needs.PreFlight.outputs.dm == 'true'
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Setup Cache
        uses: actions/cache@fd5de65bc895cf536527842281bea11763fefd77
        with:
          path: $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
          key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      - name: Run Tests
        env:
          TEST: MAP
          MAP_PATH: torch
        run: test/run-test.sh
      - name: Run Failure Webhook
        env:
          JOB_STATUS: ${{ job.status }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          HOOK_OS_NAME: ${{ runner.os }}
          WORKFLOW_NAME: ${{ github.workflow }}
        if: ${{ failure() }}
        run: |
          wget https://raw.githubusercontent.com/DiscordHooks/github-actions-discord-webhook/master/send.sh
          chmod +x send.sh
          ./send.sh failure $WEBHOOK_URL
  AwaySites:
    runs-on: ubuntu-latest
    needs: PreFlight
    if: needs.PreFlight.outputs.dm == 'true'
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: Setup Cache
        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353
        with:
          path: $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
          key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      - name: Run Tests
        env:
          TEST: MAP
          MAP_PATH: away_sites_testing
        run: test/run-test.sh
      - name: Run Failure Webhook
        env:
          JOB_STATUS: ${{ job.status }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          HOOK_OS_NAME: ${{ runner.os }}
          WORKFLOW_NAME: ${{ github.workflow }}
        if: ${{ failure() }}
        run: |
          wget https://raw.githubusercontent.com/DiscordHooks/github-actions-discord-webhook/master/send.sh
          chmod +x send.sh
          ./send.sh failure $WEBHOOK_URL
